### ISSUE TITLE
Can no longer build for platform CC3220

### ISSUE THREAD

**Issue by ulso** [cesanta/mos-tool#14]
When issuing the following command (which worked fine up to mos v2.2)
`mos build --platform cc3220 --local --libs-dir ./mos-libs --repo ../mongoose-os --clean --verbose`
I eventually get the following error message:
`Error: can't build for the platform cc3220; only those platforms are supported: [cc3200 esp32 esp8266]`

**Comment by rojer** [comment]
i'll need list of libs from your app's `mos.yml`.

**Comment by ulso** [comment]
These are the libs used:

```
libs:
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/aws
#  - origin: https://github.com/mongoose-os-libs/dash
  - origin: https://github.com/mongoose-os-libs/http-server
  - origin: https://github.com/mongoose-os-libs/ota-http-client
  - origin: https://github.com/mongoose-os-libs/ota-http-server
#  - origin: https://github.com/mongoose-os-libs/ota-shadow
  - origin: https://github.com/mongoose-os-libs/rpc-loopback
  - origin: https://github.com/mongoose-os-libs/rpc-mqtt
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-service-gpio
  - origin: https://github.com/mongoose-os-libs/rpc-service-i2c
  - origin: https://github.com/mongoose-os-libs/rpc-service-ota
  - origin: https://github.com/mongoose-os-libs/rpc-service-wifi
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/sntp
  - origin: https://github.com/mongoose-os-libs/spi
  - origin: https://github.com/mongoose-os-libs/i2c
  - origin: https://github.com/mongoose-os-libs/vfs-dev-spi-flash
  - origin: https://github.com/mongoose-os-libs/wifi

```
