### ISSUE TITLE
mos license Sys.GetUID rpc is missing

### ISSUE THREAD

**Issue by strov** [cesanta/mos-tool#31]
Sys.GetUID rpc is missing.
mos version 2.10.1

![image](https://user-images.githubusercontent.com/7889142/50457236-6fdd6e00-095a-11e9-9489-61a90973c588.png)

**Comment by cpq** [comment]
That should be fixed now.
```
mos update latest
```
then rebuild the firmware.

**Comment by rojer** [comment]
and now also fixed in release to 2.10.2

**Comment by strov** [comment]
The isssue I found in version 2.10.2
/mos/license_cmd/license.go#56

**Comment by cpq** [comment]
You'd need to rebuild the firmware as well.

**Comment by strov** [comment]
I rebuild the firmware and flash on the device.
I not found Sys.GetUID service in rpc-common/mgos_rpc.c

**Comment by cpq** [comment]
Thank you.
Could you show the output of `mos call RPC.List`, `mos version`  and the console boot log, please?

**Comment by strov** [comment]
![image](https://user-images.githubusercontent.com/7889142/50530950-4875d500-0b03-11e9-8a1d-f6304e595f57.png)

![image](https://user-images.githubusercontent.com/7889142/50530955-617e8600-0b03-11e9-92ca-d54c08bb9831.png)

boot log:
`[Dec 29 00:53:45.912] egment 1: paddr=0x00036cf8 vaddr=0x3ff80000 size=0x00000 (     0) load[0m
[Dec 29 00:53:45.912] [0;32mI (191) esp_image: segment 2: paddr=0x00036d00 vaddr=0x3ff80000 size=0x00000 (     0) load[0m
[Dec 29 00:53:45.912] [0;32mI (197) esp_image: segment 3: paddr=0x00036d08 vaddr=0x3ffb0000 size=0x024fc (  9468) load[0m
[Dec 29 00:53:45.912] [0;32mI (210) esp_image: segment 4: paddr=0x0003920c vaddr=0x3ffb24fc size=0x00000 (     0) load[0m
[Dec 29 00:53:45.912] [0;32mI (215) esp_image: segment 5: paddr=0x00039214 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[Dec 29 00:53:45.912] [0;32mI (224) esp_image: segment 6: paddr=0x0003961c vaddr=0x40080400 size=0x069f4 ( 27124) load[0m
[Dec 29 00:53:45.929] [0;32mI (244) esp_image: segment 7: paddr=0x00040018 vaddr=0x400d0018 size=0xaf9b8 (719288) map[0m
[Dec 29 00:53:46.198] [0;32mI (493) esp_image: segment 8: paddr=0x000ef9d8 vaddr=0x40086df4 size=0x0a074 ( 41076) load[0m
[Dec 29 00:53:46.231] [0;32mI (510) esp_image: segment 9: paddr=0x000f9a54 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[Dec 29 00:53:46.231] [0;32mI (510) esp_image: segment 10: paddr=0x000f9a5c vaddr=0x50000000 size=0x00000 (     0) load[0m
[Dec 29 00:53:46.231] [0;32mI (516) esp_image: segment 11: paddr=0x000f9a64 vaddr=0x50000000 size=0x00000 (     0) load[0m
[Dec 29 00:53:46.231] [0;32mI (535) boot: Loaded app from partition at offset 0x10000[0m
[Dec 29 00:53:46.232] [0;32mI (535) boot: Disabling RNG early entropy source...[0m
[Dec 29 00:53:46.232] [0;32mI (537) cpu_start: Pro cpu up.[0m
[Dec 29 00:53:46.232] [0;32mI (541) cpu_start: Single core mode[0m
[Dec 29 00:53:46.276] [0;32mI (545) heap_init: Initializing. RAM available for dynamic allocation:[0m
[Dec 29 00:53:46.276] [0;32mI (552) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
[Dec 29 00:53:46.276] [0;32mI (558) heap_init: At 3FFBA6A0 len 00025960 (150 KiB): DRAM[0m
[Dec 29 00:53:46.276] [0;32mI (564) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM[0m
[Dec 29 00:53:46.276] [0;32mI (571) heap_init: At 40078000 len 00008000 (32 KiB): IRAM[0m
[Dec 29 00:53:46.276] [0;32mI (577) heap_init: At 40090E68 len 0000F198 (60 KiB): IRAM[0m
[Dec 29 00:53:46.276] [0;32mI (583) cpu_start: Pro cpu start user code[0m
[Dec 29 00:53:46.281] [0;32mI (153) cpu_start: Starting scheduler on PRO CPU.[0m
[Dec 29 00:53:46.322] mgos_init2           Project-RAW 1.5@B (20181228-215507)
[Dec 29 00:53:46.322] mgos_init2           Mongoose OS 201812282155 (20181228-215507)
[Dec 29 00:53:46.322] mgos_init2           CPU: 240 MHz, heap: 289900 total, 258252 free
[Dec 29 00:53:46.322] mgos_init2           Newlib 2.2.0
[Dec 29 00:53:46.322] mgos_hal_freertos_pr ESP-IDF v3.2-r1
[Dec 29 00:53:46.322] mgos_hal_freertos_pr Boot partition: app_0; flash: 4M
[Dec 29 00:53:46.322] mg_lwip_if_init      Mongoose 6.13, LwIP 2.0.3
[Dec 29 00:53:46.323] mg_ssl_if_init       mbed TLS 2.13.1-cesanta2
[Dec 29 00:53:46.331] mgos_vfs_dev_create_ fs_0: esp32part ({"label": "fs_0"}), size 262144
[Dec 29 00:53:46.337] mgos_vfs_dev_create_ fs_1: esp32part ({"label": "fs_1"}), size 262144
[Dec 29 00:53:46.345] mgos_vfs_mount_dev   /: SPIFFS @ fs_0, opts {"bs": 4096, "ps": 256, "es": 4096}
[Dec 29 00:53:46.445] mgos_vfs_print_fs_in /: size 233681, used: 28865, free: 204816
[Dec 29 00:53:46.486] I (544) wifi: wifi driver task: 3ffc18d8, prio:23, stack:3584, core=0
[Dec 29 00:53:46.494] I (554) wifi: wifi firmware version: e6431f2
[Dec 29 00:53:46.494] I (564) wifi: config NVS flash: enabled
[Dec 29 00:53:46.494] I (564) wifi: config nano formating: disabled
[Dec 29 00:53:46.506] I (574) wifi: Init dynamic tx buffer num: 32
[Dec 29 00:53:46.515] I (574) wifi: Init data frame dynamic rx buffer num: 64
[Dec 29 00:53:46.515] I (584) wifi: Init management frame dynamic rx buffer num: 64
[Dec 29 00:53:46.520] I (584) wifi: Init static rx buffer size: 1600
[Dec 29 00:53:46.528] I (594) wifi: Init static rx buffer num: 10
[Dec 29 00:53:46.528] I (594) wifi: Init dynamic rx buffer num: 0
[Dec 29 00:53:46.659] [0;32mI (664) phy: phy_version: 4000, b6198fa, Sep  3 2018, 15:11:06, 0, 0[0m
[Dec 29 00:53:46.659] I (664) wifi: mode : softAP (30:ae:a4:38:8c:51)
[Dec 29 00:53:46.659] I (674) wifi: Init max length of beacon: 752/752
[Dec 29 00:53:46.659] I (684) wifi: Init max length of beacon: 752/752
[Dec 29 00:53:46.659] I (684) wifi: Set ps type: 0
[Dec 29 00:53:46.659] 
[Dec 29 00:53:46.659] I (694) wifi: mode : sta (30:ae:a4:38:8c:50)
[Dec 29 00:53:46.659] I (694) wpa: WPA2: already disabled
[Dec 29 00:53:46.659] I (704) wifi: Set ps type: 0
[Dec 29 00:53:46.659] 
[Dec 29 00:53:47.975] I (2034) wifi: n:11 0, o:1 0, ap:255 255, sta:11 0, prof:1
[Dec 29 00:53:48.539] I (2604) wifi: state: init -> auth (b0)
[Dec 29 00:53:48.542] I (2614) wifi: state: auth -> assoc (0)
[Dec 29 00:53:48.550] I (2614) wifi: state: assoc -> run (10)
[Dec 29 00:53:48.582] I (2644) wifi: connected with Avalon, channel 11
[Dec 29 00:53:48.582] I (2654) wifi: pm start, type: 0`

**Comment by cpq** [comment]
Would the following fix the problem?

```
mos update latest
mos build --platform esp32
mos flash
```

I am assuming that the `mos.yml` does not pin the version to the old one.

**Comment by strov** [comment]
I've tried this.
The problem hasn't been resolved.

![image](https://user-images.githubusercontent.com/7889142/50531634-a14a6b00-0b0d-11e9-8b08-408365e89aff.png)

![image](https://user-images.githubusercontent.com/7889142/50531640-bcb57600-0b0d-11e9-8355-a8f465cbaa32.png)

![image](https://user-images.githubusercontent.com/7889142/50531669-609f2180-0b0e-11e9-865a-a0c2796aeb30.png)


mos.yml:

`version: "1.5@B"
manifest_version: 2017-09-29

sources: [ src ]
includes: [ include ]
filesystem: [ fs ]
config_schema:
  - ["device.id", "????"]
  - ["i2c.enable", true]
  - ["i2c.sda_gpio", 21]
  - ["i2c.scl_gpio", 22]
  - ["i2c.freq", 100000]
  - ["wifi.ap.enable", false]
  - ["wifi.ap.ssid", "????"]
  - ["wifi.ap.pass", "*******"]
  - ["wifi.ap.hidden", true]
  - ["wifi.ap.max_connections", 1]
  - ["wifi.ap.ip", "192.168.4.1"]
  - ["wifi.ap.netmask", "255.255.255.0"]
  - ["wifi.ap.gw", "192.168.4.1"]
  - ["wifi.ap.dhcp_start", "192.168.4.2"]
  - ["wifi.ap.dhcp_end", "192.168.4.100"]
  - ["wifi.sta.enable", true]
  - ["wifi.sta.ssid", "*******"]
  - ["wifi.sta.pass", "*******"]
  - ["wifi.sta1.enable", true]
  - ["wifi.sta1.ssid", "*******"]
  - ["wifi.sta1.pass", "*******"]
  - ["wifi.sta2.enable", true]
  - ["wifi.sta2.ssid", "*******"]
  - ["wifi.sta2.pass", "*******"]
  - ["mqtt.enable", true]
  - ["mqtt.server", "*******"]
  - ["mqtt.keep_alive", 5]
  - ["mqtt.sub", "s", "/label", {title: "Subscribe topic"}]
  - ["debug.sub", "s", "/reset", {title: "Subscribe reset topic"}]
  - ["debug.level", 0]

libs:
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-service-i2c
  - origin: https://github.com/mongoose-os-libs/ota-http-server
  - origin: https://github.com/mongoose-os-libs/rpc-mqtt
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/i2c
  - origin: https://github.com/mongoose-os-libs/wifi
  - origin: https://github.com/mongoose-os-libs/mqtt

build_vars:
  MGOS_ENABLE_I2C_GPIO: 1
  ESP_IDF_SDKCONFIG_OPTS: "${build_vars.ESP_IDF_SDKCONFIG_OPTS} CONFIG_ESP32_DEFAULT_CPU_FREQ_160= CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240"

tags:
  - c
  - hw`

**Comment by cpq** [comment]
You have pinned build version:

```
version: "1.5@B"
```

**Comment by strov** [comment]
I've tried this.
The problem hasn't been resolved.

FW version has changed only
![image](https://user-images.githubusercontent.com/7889142/50534445-0a95a280-0b3d-11e9-879b-1c1f1efd4b17.png)

![image](https://user-images.githubusercontent.com/7889142/50534479-9dced800-0b3d-11e9-9f1b-e579fa933a75.png)


mos.yml:

```yaml
manifest_version: 2017-09-29

sources: [ src ]
includes: [ include ]
filesystem: [ fs ]
config_schema:
  - ["device.id", "????"]
  - ["i2c.enable", true]
  - ["i2c.sda_gpio", 21]
  - ["i2c.scl_gpio", 22]
  - ["i2c.freq", 100000]
  - ["wifi.ap.enable", false]
  - ["wifi.ap.ssid", "????"]
  - ["wifi.ap.pass", "*****"]
  - ["wifi.ap.hidden", true]
  - ["wifi.ap.max_connections", 1]
  - ["wifi.ap.ip", "192.168.4.1"]
  - ["wifi.ap.netmask", "255.255.255.0"]
  - ["wifi.ap.gw", "192.168.4.1"]
  - ["wifi.ap.dhcp_start", "192.168.4.2"]
  - ["wifi.ap.dhcp_end", "192.168.4.100"]
  - ["wifi.sta.enable", true]
  - ["wifi.sta.ssid", "*****"]
  - ["wifi.sta.pass", "*****"]
  - ["wifi.sta1.enable", true]
  - ["wifi.sta1.ssid", "*****"]
  - ["wifi.sta1.pass", "*****"]
  - ["wifi.sta2.enable", true]
  - ["wifi.sta2.ssid", "*****"]
  - ["wifi.sta2.pass", "*****"]
  - ["mqtt.enable", true]
  - ["mqtt.server", "*****"]
  - ["mqtt.keep_alive", 5]
  - ["mqtt.sub", "s", "/label", {title: "Subscribe topic"}]
  - ["debug.sub", "s", "/reset", {title: "Subscribe reset topic"}]
  - ["debug.level", 0]

libs:
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-service-i2c
  - origin: https://github.com/mongoose-os-libs/ota-http-server
  - origin: https://github.com/mongoose-os-libs/rpc-mqtt
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/i2c
  - origin: https://github.com/mongoose-os-libs/wifi
  - origin: https://github.com/mongoose-os-libs/mqtt

build_vars:
  MGOS_ENABLE_I2C_GPIO: 1
  ESP_IDF_SDKCONFIG_OPTS: "${build_vars.ESP_IDF_SDKCONFIG_OPTS} CONFIG_ESP32_DEFAULT_CPU_FREQ_160= CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240"

tags:
  - c
  - hw
```
